# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI: true

jobs:
  win:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include: [
          {msystem: MINGW32, toolchain: mingw-w64-i686-toolchain, version: x32 },
          {msystem: MINGW64, toolchain: mingw-w64-x86_64-toolchainn, version: x64 },
        ]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install msys2 build environment
    - uses: msys2/setup-msys2@v1
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: base-devel git ${{ matrix.toolchain }} gimp  fftw
          
    - run: git config --global core.autocrlf input
      shell: bash
      
    - uses: actions/checkout@v2
    
    - name: Build and (hopefully) install package
      shell: msys2 {0}
      run: |
        echo $(gimptool-2.0 -n --build fourier.c) -lfftw3 -O3 | sh
        cp `which libfftw3-3.dll` .
  
    - name: Get GIMP version
      shell: msys2 {0}
      run: echo "GIMPVER=$(pacman -Q  mingw-w64-i686-gimp | cut -d ' ' -f 2)" >> $GITHUB_ENV
        
    - uses: actions/upload-artifact@v2
      with:
        name: fourier-${{ env.GIMPVER }}${{ matrix.version }}
        path: |
          ./fourier.exe
          ./libfftw3-3.dll
