name: CI
on: [push,pull_request]

jobs:
  gimp2_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        choiceL: [--disable-silent-rules, --enable-silent-rules]
    steps:
      - uses: actions/checkout@v3
      - name: Create configure
        run: |
          sudo apt-get update -y
          sudo apt-get install autoconf automake libtool gcc libfftw3-dev libgimp2.0-dev
          autoreconf -i
          automake
      - name: Choose configure
        run: ./configure ${{ matrix.choiceL }}
      - name: Make fourier plugin
        run: make
      - name: Strip Debug Symbols
        run: make strip
      - name: Test user-level install/uninstall
        if: matrix.choiceL == '--disable-silent-rules'
        run: |
          make install-user
          make uninstall-user
      - name: Test make distcheck
        if: matrix.choiceL == '--disable-silent-rules'
        run: make distcheck
      - name: Test make install GIMP shared plugin
        if: matrix.choiceL == '--disable-silent-rules'
        run: |
          sudo make install
          sudo make uninstall
      - name: Build deb package
        if: matrix.choiceL == '--enable-silent-rules'
        run: make clean && ./configure && make deb && cp ../gimp-plugin-fourier_* .
      - name: Build dist
        if: matrix.choiceL == '--enable-silent-rules'
        run: ./configure && make dist
      - uses: actions/upload-artifact@v2
        with:
          name: fourier_gimp_linux
          path: |
            gimp-plugin-fourier_*
            gimp-plugin-fourier-*.tar.gz
  gimp2_win:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          {msystem: MINGW32, toolchain: mingw-w64-i686, version: x32 },
          {msystem: MINGW64, toolchain: mingw-w64-x86_64, version: x64 },
          {msystem: UCRT64, toolchain: mingw-w64-ucrt-x86_64, version: x64 },
          {msystem: CLANG64, toolchain: mingw-w64-clang-x86_64, version: x64 },
        ]
    name: gimp2_${{ matrix.msystem }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: autotools base-devel git ${{ matrix.toolchain }}-toolchain ${{ matrix.toolchain }}-gimp ${{ matrix.toolchain }}-fftw
      - name: Create configure
        run: |
          autoreconf -i
          automake
      - name: run ./configure
        run: ./configure
      - name: Make gimp-plugin-fourier
        run: make
  gimp3_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        choiceL: [--disable-silent-rules, --enable-silent-rules]
    steps:
      - uses: actions/checkout@v3
      - name: Create configure
        run: |
          sudo apt-get update -y
          sudo apt-get install autoconf automake libtool gcc libfftw3-dev libgimp-3.0-dev
          autoreconf -i
          automake
      - name: Choose configure
        run: ./configure ${{ matrix.choiceL }} --enable-gimp3-fourier
      - name: Make fourier3 plugin
        run: make
      - name: Strip Debug Symbols
        run: make strip
      - name: Test make install GIMP shared plugin
        if: matrix.choiceL == '--disable-silent-rules'
        run: |
          sudo make install
          sudo make uninstall
  gimp3_win:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include: [
          {msystem: MINGW32, toolchain: mingw-w64-i686, version: x32, gimp: "gimp", gimptool: "gimptool-2.0" },
          {msystem: MINGW64, toolchain: mingw-w64-x86_64, version: x64, gimp: "gimp", gimptool: "gimptool-2.0" },
          {msystem: MINGW64, toolchain: mingw-w64-x86_64, version: x64, gimp: "gimp3", gimptool: "gimptool-2.99" },
        ]
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install msys2 build environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: base-devel git ${{ matrix.toolchain }}-toolchain ${{ matrix.toolchain }}-${{ matrix.gimp }} ${{ matrix.toolchain }}-fftw 

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v4

    - name: Build plugin
      shell: msys2 {0}
      run: |
        echo $( ${{ matrix.gimptool }} -n --build fourier.c) -lfftw3 -O3 | sh
        cp `which libfftw3-3.dll` .

    - name: Get GIMP version
      shell: msys2 {0}
      run: echo "GIMPVER=$(pacman -Q  ${{ matrix.toolchain }}-${{ matrix.gimp }} | cut -d ' ' -f 2)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v2
      with:
        name: fourier_gimp${{ env.GIMPVER }}_${{ matrix.version }}
        path: |
          ./fourier.exe
          ./libfftw3-3.dll
